/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVouchersRouteImport } from './routes/app.vouchers'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppLedgersRouteImport } from './routes/app.ledgers'
import { Route as AppItemsRouteImport } from './routes/app.items'
import { Route as AppCompaniesRouteImport } from './routes/app.companies'
import { Route as AppVouchersNewSalesRouteImport } from './routes/app.vouchers.new.sales'
import { Route as AppVouchersNewReceiptRouteImport } from './routes/app.vouchers.new.receipt'
import { Route as AppVouchersNewPurchaseRouteImport } from './routes/app.vouchers.new.purchase'
import { Route as AppVouchersNewPaymentRouteImport } from './routes/app.vouchers.new.payment'
import { Route as AppVouchersNewJournalRouteImport } from './routes/app.vouchers.new.journal'
import { Route as AppVouchersNewDebit_noteRouteImport } from './routes/app.vouchers.new.debit_note'
import { Route as AppVouchersNewCredit_noteRouteImport } from './routes/app.vouchers.new.credit_note'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVouchersRoute = AppVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgersRoute = AppLedgersRouteImport.update({
  id: '/ledgers',
  path: '/ledgers',
  getParentRoute: () => AppRoute,
} as any)
const AppItemsRoute = AppItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppVouchersNewSalesRoute = AppVouchersNewSalesRouteImport.update({
  id: '/new/sales',
  path: '/new/sales',
  getParentRoute: () => AppVouchersRoute,
} as any)
const AppVouchersNewReceiptRoute = AppVouchersNewReceiptRouteImport.update({
  id: '/new/receipt',
  path: '/new/receipt',
  getParentRoute: () => AppVouchersRoute,
} as any)
const AppVouchersNewPurchaseRoute = AppVouchersNewPurchaseRouteImport.update({
  id: '/new/purchase',
  path: '/new/purchase',
  getParentRoute: () => AppVouchersRoute,
} as any)
const AppVouchersNewPaymentRoute = AppVouchersNewPaymentRouteImport.update({
  id: '/new/payment',
  path: '/new/payment',
  getParentRoute: () => AppVouchersRoute,
} as any)
const AppVouchersNewJournalRoute = AppVouchersNewJournalRouteImport.update({
  id: '/new/journal',
  path: '/new/journal',
  getParentRoute: () => AppVouchersRoute,
} as any)
const AppVouchersNewDebit_noteRoute =
  AppVouchersNewDebit_noteRouteImport.update({
    id: '/new/debit_note',
    path: '/new/debit_note',
    getParentRoute: () => AppVouchersRoute,
  } as any)
const AppVouchersNewCredit_noteRoute =
  AppVouchersNewCredit_noteRouteImport.update({
    id: '/new/credit_note',
    path: '/new/credit_note',
    getParentRoute: () => AppVouchersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/items': typeof AppItemsRoute
  '/app/ledgers': typeof AppLedgersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/vouchers': typeof AppVouchersRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/vouchers/new/credit_note': typeof AppVouchersNewCredit_noteRoute
  '/app/vouchers/new/debit_note': typeof AppVouchersNewDebit_noteRoute
  '/app/vouchers/new/journal': typeof AppVouchersNewJournalRoute
  '/app/vouchers/new/payment': typeof AppVouchersNewPaymentRoute
  '/app/vouchers/new/purchase': typeof AppVouchersNewPurchaseRoute
  '/app/vouchers/new/receipt': typeof AppVouchersNewReceiptRoute
  '/app/vouchers/new/sales': typeof AppVouchersNewSalesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/items': typeof AppItemsRoute
  '/app/ledgers': typeof AppLedgersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/vouchers': typeof AppVouchersRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/vouchers/new/credit_note': typeof AppVouchersNewCredit_noteRoute
  '/app/vouchers/new/debit_note': typeof AppVouchersNewDebit_noteRoute
  '/app/vouchers/new/journal': typeof AppVouchersNewJournalRoute
  '/app/vouchers/new/payment': typeof AppVouchersNewPaymentRoute
  '/app/vouchers/new/purchase': typeof AppVouchersNewPurchaseRoute
  '/app/vouchers/new/receipt': typeof AppVouchersNewReceiptRoute
  '/app/vouchers/new/sales': typeof AppVouchersNewSalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/items': typeof AppItemsRoute
  '/app/ledgers': typeof AppLedgersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/vouchers': typeof AppVouchersRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/vouchers/new/credit_note': typeof AppVouchersNewCredit_noteRoute
  '/app/vouchers/new/debit_note': typeof AppVouchersNewDebit_noteRoute
  '/app/vouchers/new/journal': typeof AppVouchersNewJournalRoute
  '/app/vouchers/new/payment': typeof AppVouchersNewPaymentRoute
  '/app/vouchers/new/purchase': typeof AppVouchersNewPurchaseRoute
  '/app/vouchers/new/receipt': typeof AppVouchersNewReceiptRoute
  '/app/vouchers/new/sales': typeof AppVouchersNewSalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/companies'
    | '/app/items'
    | '/app/ledgers'
    | '/app/reports'
    | '/app/settings'
    | '/app/vouchers'
    | '/app/'
    | '/app/vouchers/new/credit_note'
    | '/app/vouchers/new/debit_note'
    | '/app/vouchers/new/journal'
    | '/app/vouchers/new/payment'
    | '/app/vouchers/new/purchase'
    | '/app/vouchers/new/receipt'
    | '/app/vouchers/new/sales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/companies'
    | '/app/items'
    | '/app/ledgers'
    | '/app/reports'
    | '/app/settings'
    | '/app/vouchers'
    | '/app'
    | '/app/vouchers/new/credit_note'
    | '/app/vouchers/new/debit_note'
    | '/app/vouchers/new/journal'
    | '/app/vouchers/new/payment'
    | '/app/vouchers/new/purchase'
    | '/app/vouchers/new/receipt'
    | '/app/vouchers/new/sales'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/companies'
    | '/app/items'
    | '/app/ledgers'
    | '/app/reports'
    | '/app/settings'
    | '/app/vouchers'
    | '/app/'
    | '/app/vouchers/new/credit_note'
    | '/app/vouchers/new/debit_note'
    | '/app/vouchers/new/journal'
    | '/app/vouchers/new/payment'
    | '/app/vouchers/new/purchase'
    | '/app/vouchers/new/receipt'
    | '/app/vouchers/new/sales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vouchers': {
      id: '/app/vouchers'
      path: '/vouchers'
      fullPath: '/app/vouchers'
      preLoaderRoute: typeof AppVouchersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ledgers': {
      id: '/app/ledgers'
      path: '/ledgers'
      fullPath: '/app/ledgers'
      preLoaderRoute: typeof AppLedgersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/items': {
      id: '/app/items'
      path: '/items'
      fullPath: '/app/items'
      preLoaderRoute: typeof AppItemsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/companies': {
      id: '/app/companies'
      path: '/companies'
      fullPath: '/app/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vouchers/new/sales': {
      id: '/app/vouchers/new/sales'
      path: '/new/sales'
      fullPath: '/app/vouchers/new/sales'
      preLoaderRoute: typeof AppVouchersNewSalesRouteImport
      parentRoute: typeof AppVouchersRoute
    }
    '/app/vouchers/new/receipt': {
      id: '/app/vouchers/new/receipt'
      path: '/new/receipt'
      fullPath: '/app/vouchers/new/receipt'
      preLoaderRoute: typeof AppVouchersNewReceiptRouteImport
      parentRoute: typeof AppVouchersRoute
    }
    '/app/vouchers/new/purchase': {
      id: '/app/vouchers/new/purchase'
      path: '/new/purchase'
      fullPath: '/app/vouchers/new/purchase'
      preLoaderRoute: typeof AppVouchersNewPurchaseRouteImport
      parentRoute: typeof AppVouchersRoute
    }
    '/app/vouchers/new/payment': {
      id: '/app/vouchers/new/payment'
      path: '/new/payment'
      fullPath: '/app/vouchers/new/payment'
      preLoaderRoute: typeof AppVouchersNewPaymentRouteImport
      parentRoute: typeof AppVouchersRoute
    }
    '/app/vouchers/new/journal': {
      id: '/app/vouchers/new/journal'
      path: '/new/journal'
      fullPath: '/app/vouchers/new/journal'
      preLoaderRoute: typeof AppVouchersNewJournalRouteImport
      parentRoute: typeof AppVouchersRoute
    }
    '/app/vouchers/new/debit_note': {
      id: '/app/vouchers/new/debit_note'
      path: '/new/debit_note'
      fullPath: '/app/vouchers/new/debit_note'
      preLoaderRoute: typeof AppVouchersNewDebit_noteRouteImport
      parentRoute: typeof AppVouchersRoute
    }
    '/app/vouchers/new/credit_note': {
      id: '/app/vouchers/new/credit_note'
      path: '/new/credit_note'
      fullPath: '/app/vouchers/new/credit_note'
      preLoaderRoute: typeof AppVouchersNewCredit_noteRouteImport
      parentRoute: typeof AppVouchersRoute
    }
  }
}

interface AppVouchersRouteChildren {
  AppVouchersNewCredit_noteRoute: typeof AppVouchersNewCredit_noteRoute
  AppVouchersNewDebit_noteRoute: typeof AppVouchersNewDebit_noteRoute
  AppVouchersNewJournalRoute: typeof AppVouchersNewJournalRoute
  AppVouchersNewPaymentRoute: typeof AppVouchersNewPaymentRoute
  AppVouchersNewPurchaseRoute: typeof AppVouchersNewPurchaseRoute
  AppVouchersNewReceiptRoute: typeof AppVouchersNewReceiptRoute
  AppVouchersNewSalesRoute: typeof AppVouchersNewSalesRoute
}

const AppVouchersRouteChildren: AppVouchersRouteChildren = {
  AppVouchersNewCredit_noteRoute: AppVouchersNewCredit_noteRoute,
  AppVouchersNewDebit_noteRoute: AppVouchersNewDebit_noteRoute,
  AppVouchersNewJournalRoute: AppVouchersNewJournalRoute,
  AppVouchersNewPaymentRoute: AppVouchersNewPaymentRoute,
  AppVouchersNewPurchaseRoute: AppVouchersNewPurchaseRoute,
  AppVouchersNewReceiptRoute: AppVouchersNewReceiptRoute,
  AppVouchersNewSalesRoute: AppVouchersNewSalesRoute,
}

const AppVouchersRouteWithChildren = AppVouchersRoute._addFileChildren(
  AppVouchersRouteChildren,
)

interface AppRouteChildren {
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppItemsRoute: typeof AppItemsRoute
  AppLedgersRoute: typeof AppLedgersRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVouchersRoute: typeof AppVouchersRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompaniesRoute: AppCompaniesRoute,
  AppItemsRoute: AppItemsRoute,
  AppLedgersRoute: AppLedgersRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVouchersRoute: AppVouchersRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
