/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVouchersRouteImport } from './routes/app.vouchers'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRecurringRouteImport } from './routes/app.recurring'
import { Route as AppLedgersRouteImport } from './routes/app.ledgers'
import { Route as AppItemsRouteImport } from './routes/app.items'
import { Route as AppHousekeepingRouteImport } from './routes/app.housekeeping'
import { Route as AppEinvoiceRouteImport } from './routes/app.einvoice'
import { Route as AppCompaniesRouteImport } from './routes/app.companies'
import { Route as AppBankRouteImport } from './routes/app.bank'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppAccountGroupsRouteImport } from './routes/app.account-groups'
import { Route as AppVouchersVoucherIdRouteImport } from './routes/app.vouchers.$voucherId'
import { Route as AppReportsTrialBalanceRouteImport } from './routes/app.reports.trial-balance'
import { Route as AppReportsTradingRouteImport } from './routes/app.reports.trading'
import { Route as AppReportsStockSummaryRouteImport } from './routes/app.reports.stock-summary'
import { Route as AppReportsSalesRegisterRouteImport } from './routes/app.reports.sales-register'
import { Route as AppReportsReceivablesRouteImport } from './routes/app.reports.receivables'
import { Route as AppReportsPurchaseRegisterRouteImport } from './routes/app.reports.purchase-register'
import { Route as AppReportsProfitLossRouteImport } from './routes/app.reports.profit-loss'
import { Route as AppReportsPayablesRouteImport } from './routes/app.reports.payables'
import { Route as AppReportsOutstandingRouteImport } from './routes/app.reports.outstanding'
import { Route as AppReportsLedgerRouteImport } from './routes/app.reports.ledger'
import { Route as AppReportsGstr3bRouteImport } from './routes/app.reports.gstr3b'
import { Route as AppReportsGstr2bRouteImport } from './routes/app.reports.gstr2b'
import { Route as AppReportsGstr1RouteImport } from './routes/app.reports.gstr1'
import { Route as AppReportsGstSalesBookRouteImport } from './routes/app.reports.gst-sales-book'
import { Route as AppReportsGstPurchaseBookRouteImport } from './routes/app.reports.gst-purchase-book'
import { Route as AppReportsGroupLedgerRouteImport } from './routes/app.reports.group-ledger'
import { Route as AppReportsDayBookRouteImport } from './routes/app.reports.day-book'
import { Route as AppReportsCashBankRouteImport } from './routes/app.reports.cash-bank'
import { Route as AppReportsBrsRouteImport } from './routes/app.reports.brs'
import { Route as AppReportsBalanceSheetRouteImport } from './routes/app.reports.balance-sheet'
import { Route as AppReportsAgeingRouteImport } from './routes/app.reports.ageing'
import { Route as AppVouchersNewSales_orderRouteImport } from './routes/app.vouchers.new.sales_order'
import { Route as AppVouchersNewSalesRouteImport } from './routes/app.vouchers.new.sales'
import { Route as AppVouchersNewReceiptRouteImport } from './routes/app.vouchers.new.receipt'
import { Route as AppVouchersNewQuotationRouteImport } from './routes/app.vouchers.new.quotation'
import { Route as AppVouchersNewPurchaseRouteImport } from './routes/app.vouchers.new.purchase'
import { Route as AppVouchersNewPaymentRouteImport } from './routes/app.vouchers.new.payment'
import { Route as AppVouchersNewManufacturingRouteImport } from './routes/app.vouchers.new.manufacturing'
import { Route as AppVouchersNewJournalRouteImport } from './routes/app.vouchers.new.journal'
import { Route as AppVouchersNewDelivery_noteRouteImport } from './routes/app.vouchers.new.delivery_note'
import { Route as AppVouchersNewDebit_noteRouteImport } from './routes/app.vouchers.new.debit_note'
import { Route as AppVouchersNewCredit_noteRouteImport } from './routes/app.vouchers.new.credit_note'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVouchersRoute = AppVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRecurringRoute = AppRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgersRoute = AppLedgersRouteImport.update({
  id: '/ledgers',
  path: '/ledgers',
  getParentRoute: () => AppRoute,
} as any)
const AppItemsRoute = AppItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppRoute,
} as any)
const AppHousekeepingRoute = AppHousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => AppRoute,
} as any)
const AppEinvoiceRoute = AppEinvoiceRouteImport.update({
  id: '/einvoice',
  path: '/einvoice',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppBankRoute = AppBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountGroupsRoute = AppAccountGroupsRouteImport.update({
  id: '/account-groups',
  path: '/account-groups',
  getParentRoute: () => AppRoute,
} as any)
const AppVouchersVoucherIdRoute = AppVouchersVoucherIdRouteImport.update({
  id: '/$voucherId',
  path: '/$voucherId',
  getParentRoute: () => AppVouchersRoute,
} as any)
const AppReportsTrialBalanceRoute = AppReportsTrialBalanceRouteImport.update({
  id: '/trial-balance',
  path: '/trial-balance',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsTradingRoute = AppReportsTradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsStockSummaryRoute = AppReportsStockSummaryRouteImport.update({
  id: '/stock-summary',
  path: '/stock-summary',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsSalesRegisterRoute = AppReportsSalesRegisterRouteImport.update({
  id: '/sales-register',
  path: '/sales-register',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsReceivablesRoute = AppReportsReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsPurchaseRegisterRoute =
  AppReportsPurchaseRegisterRouteImport.update({
    id: '/purchase-register',
    path: '/purchase-register',
    getParentRoute: () => AppReportsRoute,
  } as any)
const AppReportsProfitLossRoute = AppReportsProfitLossRouteImport.update({
  id: '/profit-loss',
  path: '/profit-loss',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsPayablesRoute = AppReportsPayablesRouteImport.update({
  id: '/payables',
  path: '/payables',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsOutstandingRoute = AppReportsOutstandingRouteImport.update({
  id: '/outstanding',
  path: '/outstanding',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsLedgerRoute = AppReportsLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsGstr3bRoute = AppReportsGstr3bRouteImport.update({
  id: '/gstr3b',
  path: '/gstr3b',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsGstr2bRoute = AppReportsGstr2bRouteImport.update({
  id: '/gstr2b',
  path: '/gstr2b',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsGstr1Route = AppReportsGstr1RouteImport.update({
  id: '/gstr1',
  path: '/gstr1',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsGstSalesBookRoute = AppReportsGstSalesBookRouteImport.update({
  id: '/gst-sales-book',
  path: '/gst-sales-book',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsGstPurchaseBookRoute =
  AppReportsGstPurchaseBookRouteImport.update({
    id: '/gst-purchase-book',
    path: '/gst-purchase-book',
    getParentRoute: () => AppReportsRoute,
  } as any)
const AppReportsGroupLedgerRoute = AppReportsGroupLedgerRouteImport.update({
  id: '/group-ledger',
  path: '/group-ledger',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsDayBookRoute = AppReportsDayBookRouteImport.update({
  id: '/day-book',
  path: '/day-book',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsCashBankRoute = AppReportsCashBankRouteImport.update({
  id: '/cash-bank',
  path: '/cash-bank',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsBrsRoute = AppReportsBrsRouteImport.update({
  id: '/brs',
  path: '/brs',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsBalanceSheetRoute = AppReportsBalanceSheetRouteImport.update({
  id: '/balance-sheet',
  path: '/balance-sheet',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsAgeingRoute = AppReportsAgeingRouteImport.update({
  id: '/ageing',
  path: '/ageing',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppVouchersNewSales_orderRoute =
  AppVouchersNewSales_orderRouteImport.update({
    id: '/new/sales_order',
    path: '/new/sales_order',
    getParentRoute: () => AppVouchersRoute,
  } as any)
const AppVouchersNewSalesRoute = AppVouchersNewSalesRouteImport.update({
  id: '/new/sales',
  path: '/new/sales',
  getParentRoute: () => AppVouchersRoute,
} as any)
const AppVouchersNewReceiptRoute = AppVouchersNewReceiptRouteImport.update({
  id: '/new/receipt',
  path: '/new/receipt',
  getParentRoute: () => AppVouchersRoute,
} as any)
const AppVouchersNewQuotationRoute = AppVouchersNewQuotationRouteImport.update({
  id: '/new/quotation',
  path: '/new/quotation',
  getParentRoute: () => AppVouchersRoute,
} as any)
const AppVouchersNewPurchaseRoute = AppVouchersNewPurchaseRouteImport.update({
  id: '/new/purchase',
  path: '/new/purchase',
  getParentRoute: () => AppVouchersRoute,
} as any)
const AppVouchersNewPaymentRoute = AppVouchersNewPaymentRouteImport.update({
  id: '/new/payment',
  path: '/new/payment',
  getParentRoute: () => AppVouchersRoute,
} as any)
const AppVouchersNewManufacturingRoute =
  AppVouchersNewManufacturingRouteImport.update({
    id: '/new/manufacturing',
    path: '/new/manufacturing',
    getParentRoute: () => AppVouchersRoute,
  } as any)
const AppVouchersNewJournalRoute = AppVouchersNewJournalRouteImport.update({
  id: '/new/journal',
  path: '/new/journal',
  getParentRoute: () => AppVouchersRoute,
} as any)
const AppVouchersNewDelivery_noteRoute =
  AppVouchersNewDelivery_noteRouteImport.update({
    id: '/new/delivery_note',
    path: '/new/delivery_note',
    getParentRoute: () => AppVouchersRoute,
  } as any)
const AppVouchersNewDebit_noteRoute =
  AppVouchersNewDebit_noteRouteImport.update({
    id: '/new/debit_note',
    path: '/new/debit_note',
    getParentRoute: () => AppVouchersRoute,
  } as any)
const AppVouchersNewCredit_noteRoute =
  AppVouchersNewCredit_noteRouteImport.update({
    id: '/new/credit_note',
    path: '/new/credit_note',
    getParentRoute: () => AppVouchersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/account-groups': typeof AppAccountGroupsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/bank': typeof AppBankRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/einvoice': typeof AppEinvoiceRoute
  '/app/housekeeping': typeof AppHousekeepingRoute
  '/app/items': typeof AppItemsRoute
  '/app/ledgers': typeof AppLedgersRoute
  '/app/recurring': typeof AppRecurringRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/vouchers': typeof AppVouchersRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/reports/ageing': typeof AppReportsAgeingRoute
  '/app/reports/balance-sheet': typeof AppReportsBalanceSheetRoute
  '/app/reports/brs': typeof AppReportsBrsRoute
  '/app/reports/cash-bank': typeof AppReportsCashBankRoute
  '/app/reports/day-book': typeof AppReportsDayBookRoute
  '/app/reports/group-ledger': typeof AppReportsGroupLedgerRoute
  '/app/reports/gst-purchase-book': typeof AppReportsGstPurchaseBookRoute
  '/app/reports/gst-sales-book': typeof AppReportsGstSalesBookRoute
  '/app/reports/gstr1': typeof AppReportsGstr1Route
  '/app/reports/gstr2b': typeof AppReportsGstr2bRoute
  '/app/reports/gstr3b': typeof AppReportsGstr3bRoute
  '/app/reports/ledger': typeof AppReportsLedgerRoute
  '/app/reports/outstanding': typeof AppReportsOutstandingRoute
  '/app/reports/payables': typeof AppReportsPayablesRoute
  '/app/reports/profit-loss': typeof AppReportsProfitLossRoute
  '/app/reports/purchase-register': typeof AppReportsPurchaseRegisterRoute
  '/app/reports/receivables': typeof AppReportsReceivablesRoute
  '/app/reports/sales-register': typeof AppReportsSalesRegisterRoute
  '/app/reports/stock-summary': typeof AppReportsStockSummaryRoute
  '/app/reports/trading': typeof AppReportsTradingRoute
  '/app/reports/trial-balance': typeof AppReportsTrialBalanceRoute
  '/app/vouchers/$voucherId': typeof AppVouchersVoucherIdRoute
  '/app/vouchers/new/credit_note': typeof AppVouchersNewCredit_noteRoute
  '/app/vouchers/new/debit_note': typeof AppVouchersNewDebit_noteRoute
  '/app/vouchers/new/delivery_note': typeof AppVouchersNewDelivery_noteRoute
  '/app/vouchers/new/journal': typeof AppVouchersNewJournalRoute
  '/app/vouchers/new/manufacturing': typeof AppVouchersNewManufacturingRoute
  '/app/vouchers/new/payment': typeof AppVouchersNewPaymentRoute
  '/app/vouchers/new/purchase': typeof AppVouchersNewPurchaseRoute
  '/app/vouchers/new/quotation': typeof AppVouchersNewQuotationRoute
  '/app/vouchers/new/receipt': typeof AppVouchersNewReceiptRoute
  '/app/vouchers/new/sales': typeof AppVouchersNewSalesRoute
  '/app/vouchers/new/sales_order': typeof AppVouchersNewSales_orderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/account-groups': typeof AppAccountGroupsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/bank': typeof AppBankRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/einvoice': typeof AppEinvoiceRoute
  '/app/housekeeping': typeof AppHousekeepingRoute
  '/app/items': typeof AppItemsRoute
  '/app/ledgers': typeof AppLedgersRoute
  '/app/recurring': typeof AppRecurringRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/vouchers': typeof AppVouchersRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/reports/ageing': typeof AppReportsAgeingRoute
  '/app/reports/balance-sheet': typeof AppReportsBalanceSheetRoute
  '/app/reports/brs': typeof AppReportsBrsRoute
  '/app/reports/cash-bank': typeof AppReportsCashBankRoute
  '/app/reports/day-book': typeof AppReportsDayBookRoute
  '/app/reports/group-ledger': typeof AppReportsGroupLedgerRoute
  '/app/reports/gst-purchase-book': typeof AppReportsGstPurchaseBookRoute
  '/app/reports/gst-sales-book': typeof AppReportsGstSalesBookRoute
  '/app/reports/gstr1': typeof AppReportsGstr1Route
  '/app/reports/gstr2b': typeof AppReportsGstr2bRoute
  '/app/reports/gstr3b': typeof AppReportsGstr3bRoute
  '/app/reports/ledger': typeof AppReportsLedgerRoute
  '/app/reports/outstanding': typeof AppReportsOutstandingRoute
  '/app/reports/payables': typeof AppReportsPayablesRoute
  '/app/reports/profit-loss': typeof AppReportsProfitLossRoute
  '/app/reports/purchase-register': typeof AppReportsPurchaseRegisterRoute
  '/app/reports/receivables': typeof AppReportsReceivablesRoute
  '/app/reports/sales-register': typeof AppReportsSalesRegisterRoute
  '/app/reports/stock-summary': typeof AppReportsStockSummaryRoute
  '/app/reports/trading': typeof AppReportsTradingRoute
  '/app/reports/trial-balance': typeof AppReportsTrialBalanceRoute
  '/app/vouchers/$voucherId': typeof AppVouchersVoucherIdRoute
  '/app/vouchers/new/credit_note': typeof AppVouchersNewCredit_noteRoute
  '/app/vouchers/new/debit_note': typeof AppVouchersNewDebit_noteRoute
  '/app/vouchers/new/delivery_note': typeof AppVouchersNewDelivery_noteRoute
  '/app/vouchers/new/journal': typeof AppVouchersNewJournalRoute
  '/app/vouchers/new/manufacturing': typeof AppVouchersNewManufacturingRoute
  '/app/vouchers/new/payment': typeof AppVouchersNewPaymentRoute
  '/app/vouchers/new/purchase': typeof AppVouchersNewPurchaseRoute
  '/app/vouchers/new/quotation': typeof AppVouchersNewQuotationRoute
  '/app/vouchers/new/receipt': typeof AppVouchersNewReceiptRoute
  '/app/vouchers/new/sales': typeof AppVouchersNewSalesRoute
  '/app/vouchers/new/sales_order': typeof AppVouchersNewSales_orderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/account-groups': typeof AppAccountGroupsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/bank': typeof AppBankRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/einvoice': typeof AppEinvoiceRoute
  '/app/housekeeping': typeof AppHousekeepingRoute
  '/app/items': typeof AppItemsRoute
  '/app/ledgers': typeof AppLedgersRoute
  '/app/recurring': typeof AppRecurringRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/vouchers': typeof AppVouchersRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/reports/ageing': typeof AppReportsAgeingRoute
  '/app/reports/balance-sheet': typeof AppReportsBalanceSheetRoute
  '/app/reports/brs': typeof AppReportsBrsRoute
  '/app/reports/cash-bank': typeof AppReportsCashBankRoute
  '/app/reports/day-book': typeof AppReportsDayBookRoute
  '/app/reports/group-ledger': typeof AppReportsGroupLedgerRoute
  '/app/reports/gst-purchase-book': typeof AppReportsGstPurchaseBookRoute
  '/app/reports/gst-sales-book': typeof AppReportsGstSalesBookRoute
  '/app/reports/gstr1': typeof AppReportsGstr1Route
  '/app/reports/gstr2b': typeof AppReportsGstr2bRoute
  '/app/reports/gstr3b': typeof AppReportsGstr3bRoute
  '/app/reports/ledger': typeof AppReportsLedgerRoute
  '/app/reports/outstanding': typeof AppReportsOutstandingRoute
  '/app/reports/payables': typeof AppReportsPayablesRoute
  '/app/reports/profit-loss': typeof AppReportsProfitLossRoute
  '/app/reports/purchase-register': typeof AppReportsPurchaseRegisterRoute
  '/app/reports/receivables': typeof AppReportsReceivablesRoute
  '/app/reports/sales-register': typeof AppReportsSalesRegisterRoute
  '/app/reports/stock-summary': typeof AppReportsStockSummaryRoute
  '/app/reports/trading': typeof AppReportsTradingRoute
  '/app/reports/trial-balance': typeof AppReportsTrialBalanceRoute
  '/app/vouchers/$voucherId': typeof AppVouchersVoucherIdRoute
  '/app/vouchers/new/credit_note': typeof AppVouchersNewCredit_noteRoute
  '/app/vouchers/new/debit_note': typeof AppVouchersNewDebit_noteRoute
  '/app/vouchers/new/delivery_note': typeof AppVouchersNewDelivery_noteRoute
  '/app/vouchers/new/journal': typeof AppVouchersNewJournalRoute
  '/app/vouchers/new/manufacturing': typeof AppVouchersNewManufacturingRoute
  '/app/vouchers/new/payment': typeof AppVouchersNewPaymentRoute
  '/app/vouchers/new/purchase': typeof AppVouchersNewPurchaseRoute
  '/app/vouchers/new/quotation': typeof AppVouchersNewQuotationRoute
  '/app/vouchers/new/receipt': typeof AppVouchersNewReceiptRoute
  '/app/vouchers/new/sales': typeof AppVouchersNewSalesRoute
  '/app/vouchers/new/sales_order': typeof AppVouchersNewSales_orderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/account-groups'
    | '/app/assistant'
    | '/app/bank'
    | '/app/companies'
    | '/app/einvoice'
    | '/app/housekeeping'
    | '/app/items'
    | '/app/ledgers'
    | '/app/recurring'
    | '/app/reports'
    | '/app/settings'
    | '/app/vouchers'
    | '/app/'
    | '/app/reports/ageing'
    | '/app/reports/balance-sheet'
    | '/app/reports/brs'
    | '/app/reports/cash-bank'
    | '/app/reports/day-book'
    | '/app/reports/group-ledger'
    | '/app/reports/gst-purchase-book'
    | '/app/reports/gst-sales-book'
    | '/app/reports/gstr1'
    | '/app/reports/gstr2b'
    | '/app/reports/gstr3b'
    | '/app/reports/ledger'
    | '/app/reports/outstanding'
    | '/app/reports/payables'
    | '/app/reports/profit-loss'
    | '/app/reports/purchase-register'
    | '/app/reports/receivables'
    | '/app/reports/sales-register'
    | '/app/reports/stock-summary'
    | '/app/reports/trading'
    | '/app/reports/trial-balance'
    | '/app/vouchers/$voucherId'
    | '/app/vouchers/new/credit_note'
    | '/app/vouchers/new/debit_note'
    | '/app/vouchers/new/delivery_note'
    | '/app/vouchers/new/journal'
    | '/app/vouchers/new/manufacturing'
    | '/app/vouchers/new/payment'
    | '/app/vouchers/new/purchase'
    | '/app/vouchers/new/quotation'
    | '/app/vouchers/new/receipt'
    | '/app/vouchers/new/sales'
    | '/app/vouchers/new/sales_order'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/account-groups'
    | '/app/assistant'
    | '/app/bank'
    | '/app/companies'
    | '/app/einvoice'
    | '/app/housekeeping'
    | '/app/items'
    | '/app/ledgers'
    | '/app/recurring'
    | '/app/reports'
    | '/app/settings'
    | '/app/vouchers'
    | '/app'
    | '/app/reports/ageing'
    | '/app/reports/balance-sheet'
    | '/app/reports/brs'
    | '/app/reports/cash-bank'
    | '/app/reports/day-book'
    | '/app/reports/group-ledger'
    | '/app/reports/gst-purchase-book'
    | '/app/reports/gst-sales-book'
    | '/app/reports/gstr1'
    | '/app/reports/gstr2b'
    | '/app/reports/gstr3b'
    | '/app/reports/ledger'
    | '/app/reports/outstanding'
    | '/app/reports/payables'
    | '/app/reports/profit-loss'
    | '/app/reports/purchase-register'
    | '/app/reports/receivables'
    | '/app/reports/sales-register'
    | '/app/reports/stock-summary'
    | '/app/reports/trading'
    | '/app/reports/trial-balance'
    | '/app/vouchers/$voucherId'
    | '/app/vouchers/new/credit_note'
    | '/app/vouchers/new/debit_note'
    | '/app/vouchers/new/delivery_note'
    | '/app/vouchers/new/journal'
    | '/app/vouchers/new/manufacturing'
    | '/app/vouchers/new/payment'
    | '/app/vouchers/new/purchase'
    | '/app/vouchers/new/quotation'
    | '/app/vouchers/new/receipt'
    | '/app/vouchers/new/sales'
    | '/app/vouchers/new/sales_order'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/account-groups'
    | '/app/assistant'
    | '/app/bank'
    | '/app/companies'
    | '/app/einvoice'
    | '/app/housekeeping'
    | '/app/items'
    | '/app/ledgers'
    | '/app/recurring'
    | '/app/reports'
    | '/app/settings'
    | '/app/vouchers'
    | '/app/'
    | '/app/reports/ageing'
    | '/app/reports/balance-sheet'
    | '/app/reports/brs'
    | '/app/reports/cash-bank'
    | '/app/reports/day-book'
    | '/app/reports/group-ledger'
    | '/app/reports/gst-purchase-book'
    | '/app/reports/gst-sales-book'
    | '/app/reports/gstr1'
    | '/app/reports/gstr2b'
    | '/app/reports/gstr3b'
    | '/app/reports/ledger'
    | '/app/reports/outstanding'
    | '/app/reports/payables'
    | '/app/reports/profit-loss'
    | '/app/reports/purchase-register'
    | '/app/reports/receivables'
    | '/app/reports/sales-register'
    | '/app/reports/stock-summary'
    | '/app/reports/trading'
    | '/app/reports/trial-balance'
    | '/app/vouchers/$voucherId'
    | '/app/vouchers/new/credit_note'
    | '/app/vouchers/new/debit_note'
    | '/app/vouchers/new/delivery_note'
    | '/app/vouchers/new/journal'
    | '/app/vouchers/new/manufacturing'
    | '/app/vouchers/new/payment'
    | '/app/vouchers/new/purchase'
    | '/app/vouchers/new/quotation'
    | '/app/vouchers/new/receipt'
    | '/app/vouchers/new/sales'
    | '/app/vouchers/new/sales_order'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vouchers': {
      id: '/app/vouchers'
      path: '/vouchers'
      fullPath: '/app/vouchers'
      preLoaderRoute: typeof AppVouchersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recurring': {
      id: '/app/recurring'
      path: '/recurring'
      fullPath: '/app/recurring'
      preLoaderRoute: typeof AppRecurringRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ledgers': {
      id: '/app/ledgers'
      path: '/ledgers'
      fullPath: '/app/ledgers'
      preLoaderRoute: typeof AppLedgersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/items': {
      id: '/app/items'
      path: '/items'
      fullPath: '/app/items'
      preLoaderRoute: typeof AppItemsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/housekeeping': {
      id: '/app/housekeeping'
      path: '/housekeeping'
      fullPath: '/app/housekeeping'
      preLoaderRoute: typeof AppHousekeepingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/einvoice': {
      id: '/app/einvoice'
      path: '/einvoice'
      fullPath: '/app/einvoice'
      preLoaderRoute: typeof AppEinvoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/companies': {
      id: '/app/companies'
      path: '/companies'
      fullPath: '/app/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bank': {
      id: '/app/bank'
      path: '/bank'
      fullPath: '/app/bank'
      preLoaderRoute: typeof AppBankRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account-groups': {
      id: '/app/account-groups'
      path: '/account-groups'
      fullPath: '/app/account-groups'
      preLoaderRoute: typeof AppAccountGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vouchers/$voucherId': {
      id: '/app/vouchers/$voucherId'
      path: '/$voucherId'
      fullPath: '/app/vouchers/$voucherId'
      preLoaderRoute: typeof AppVouchersVoucherIdRouteImport
      parentRoute: typeof AppVouchersRoute
    }
    '/app/reports/trial-balance': {
      id: '/app/reports/trial-balance'
      path: '/trial-balance'
      fullPath: '/app/reports/trial-balance'
      preLoaderRoute: typeof AppReportsTrialBalanceRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/trading': {
      id: '/app/reports/trading'
      path: '/trading'
      fullPath: '/app/reports/trading'
      preLoaderRoute: typeof AppReportsTradingRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/stock-summary': {
      id: '/app/reports/stock-summary'
      path: '/stock-summary'
      fullPath: '/app/reports/stock-summary'
      preLoaderRoute: typeof AppReportsStockSummaryRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/sales-register': {
      id: '/app/reports/sales-register'
      path: '/sales-register'
      fullPath: '/app/reports/sales-register'
      preLoaderRoute: typeof AppReportsSalesRegisterRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/receivables': {
      id: '/app/reports/receivables'
      path: '/receivables'
      fullPath: '/app/reports/receivables'
      preLoaderRoute: typeof AppReportsReceivablesRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/purchase-register': {
      id: '/app/reports/purchase-register'
      path: '/purchase-register'
      fullPath: '/app/reports/purchase-register'
      preLoaderRoute: typeof AppReportsPurchaseRegisterRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/profit-loss': {
      id: '/app/reports/profit-loss'
      path: '/profit-loss'
      fullPath: '/app/reports/profit-loss'
      preLoaderRoute: typeof AppReportsProfitLossRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/payables': {
      id: '/app/reports/payables'
      path: '/payables'
      fullPath: '/app/reports/payables'
      preLoaderRoute: typeof AppReportsPayablesRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/outstanding': {
      id: '/app/reports/outstanding'
      path: '/outstanding'
      fullPath: '/app/reports/outstanding'
      preLoaderRoute: typeof AppReportsOutstandingRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/ledger': {
      id: '/app/reports/ledger'
      path: '/ledger'
      fullPath: '/app/reports/ledger'
      preLoaderRoute: typeof AppReportsLedgerRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/gstr3b': {
      id: '/app/reports/gstr3b'
      path: '/gstr3b'
      fullPath: '/app/reports/gstr3b'
      preLoaderRoute: typeof AppReportsGstr3bRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/gstr2b': {
      id: '/app/reports/gstr2b'
      path: '/gstr2b'
      fullPath: '/app/reports/gstr2b'
      preLoaderRoute: typeof AppReportsGstr2bRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/gstr1': {
      id: '/app/reports/gstr1'
      path: '/gstr1'
      fullPath: '/app/reports/gstr1'
      preLoaderRoute: typeof AppReportsGstr1RouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/gst-sales-book': {
      id: '/app/reports/gst-sales-book'
      path: '/gst-sales-book'
      fullPath: '/app/reports/gst-sales-book'
      preLoaderRoute: typeof AppReportsGstSalesBookRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/gst-purchase-book': {
      id: '/app/reports/gst-purchase-book'
      path: '/gst-purchase-book'
      fullPath: '/app/reports/gst-purchase-book'
      preLoaderRoute: typeof AppReportsGstPurchaseBookRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/group-ledger': {
      id: '/app/reports/group-ledger'
      path: '/group-ledger'
      fullPath: '/app/reports/group-ledger'
      preLoaderRoute: typeof AppReportsGroupLedgerRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/day-book': {
      id: '/app/reports/day-book'
      path: '/day-book'
      fullPath: '/app/reports/day-book'
      preLoaderRoute: typeof AppReportsDayBookRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/cash-bank': {
      id: '/app/reports/cash-bank'
      path: '/cash-bank'
      fullPath: '/app/reports/cash-bank'
      preLoaderRoute: typeof AppReportsCashBankRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/brs': {
      id: '/app/reports/brs'
      path: '/brs'
      fullPath: '/app/reports/brs'
      preLoaderRoute: typeof AppReportsBrsRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/balance-sheet': {
      id: '/app/reports/balance-sheet'
      path: '/balance-sheet'
      fullPath: '/app/reports/balance-sheet'
      preLoaderRoute: typeof AppReportsBalanceSheetRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/ageing': {
      id: '/app/reports/ageing'
      path: '/ageing'
      fullPath: '/app/reports/ageing'
      preLoaderRoute: typeof AppReportsAgeingRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/vouchers/new/sales_order': {
      id: '/app/vouchers/new/sales_order'
      path: '/new/sales_order'
      fullPath: '/app/vouchers/new/sales_order'
      preLoaderRoute: typeof AppVouchersNewSales_orderRouteImport
      parentRoute: typeof AppVouchersRoute
    }
    '/app/vouchers/new/sales': {
      id: '/app/vouchers/new/sales'
      path: '/new/sales'
      fullPath: '/app/vouchers/new/sales'
      preLoaderRoute: typeof AppVouchersNewSalesRouteImport
      parentRoute: typeof AppVouchersRoute
    }
    '/app/vouchers/new/receipt': {
      id: '/app/vouchers/new/receipt'
      path: '/new/receipt'
      fullPath: '/app/vouchers/new/receipt'
      preLoaderRoute: typeof AppVouchersNewReceiptRouteImport
      parentRoute: typeof AppVouchersRoute
    }
    '/app/vouchers/new/quotation': {
      id: '/app/vouchers/new/quotation'
      path: '/new/quotation'
      fullPath: '/app/vouchers/new/quotation'
      preLoaderRoute: typeof AppVouchersNewQuotationRouteImport
      parentRoute: typeof AppVouchersRoute
    }
    '/app/vouchers/new/purchase': {
      id: '/app/vouchers/new/purchase'
      path: '/new/purchase'
      fullPath: '/app/vouchers/new/purchase'
      preLoaderRoute: typeof AppVouchersNewPurchaseRouteImport
      parentRoute: typeof AppVouchersRoute
    }
    '/app/vouchers/new/payment': {
      id: '/app/vouchers/new/payment'
      path: '/new/payment'
      fullPath: '/app/vouchers/new/payment'
      preLoaderRoute: typeof AppVouchersNewPaymentRouteImport
      parentRoute: typeof AppVouchersRoute
    }
    '/app/vouchers/new/manufacturing': {
      id: '/app/vouchers/new/manufacturing'
      path: '/new/manufacturing'
      fullPath: '/app/vouchers/new/manufacturing'
      preLoaderRoute: typeof AppVouchersNewManufacturingRouteImport
      parentRoute: typeof AppVouchersRoute
    }
    '/app/vouchers/new/journal': {
      id: '/app/vouchers/new/journal'
      path: '/new/journal'
      fullPath: '/app/vouchers/new/journal'
      preLoaderRoute: typeof AppVouchersNewJournalRouteImport
      parentRoute: typeof AppVouchersRoute
    }
    '/app/vouchers/new/delivery_note': {
      id: '/app/vouchers/new/delivery_note'
      path: '/new/delivery_note'
      fullPath: '/app/vouchers/new/delivery_note'
      preLoaderRoute: typeof AppVouchersNewDelivery_noteRouteImport
      parentRoute: typeof AppVouchersRoute
    }
    '/app/vouchers/new/debit_note': {
      id: '/app/vouchers/new/debit_note'
      path: '/new/debit_note'
      fullPath: '/app/vouchers/new/debit_note'
      preLoaderRoute: typeof AppVouchersNewDebit_noteRouteImport
      parentRoute: typeof AppVouchersRoute
    }
    '/app/vouchers/new/credit_note': {
      id: '/app/vouchers/new/credit_note'
      path: '/new/credit_note'
      fullPath: '/app/vouchers/new/credit_note'
      preLoaderRoute: typeof AppVouchersNewCredit_noteRouteImport
      parentRoute: typeof AppVouchersRoute
    }
  }
}

interface AppReportsRouteChildren {
  AppReportsAgeingRoute: typeof AppReportsAgeingRoute
  AppReportsBalanceSheetRoute: typeof AppReportsBalanceSheetRoute
  AppReportsBrsRoute: typeof AppReportsBrsRoute
  AppReportsCashBankRoute: typeof AppReportsCashBankRoute
  AppReportsDayBookRoute: typeof AppReportsDayBookRoute
  AppReportsGroupLedgerRoute: typeof AppReportsGroupLedgerRoute
  AppReportsGstPurchaseBookRoute: typeof AppReportsGstPurchaseBookRoute
  AppReportsGstSalesBookRoute: typeof AppReportsGstSalesBookRoute
  AppReportsGstr1Route: typeof AppReportsGstr1Route
  AppReportsGstr2bRoute: typeof AppReportsGstr2bRoute
  AppReportsGstr3bRoute: typeof AppReportsGstr3bRoute
  AppReportsLedgerRoute: typeof AppReportsLedgerRoute
  AppReportsOutstandingRoute: typeof AppReportsOutstandingRoute
  AppReportsPayablesRoute: typeof AppReportsPayablesRoute
  AppReportsProfitLossRoute: typeof AppReportsProfitLossRoute
  AppReportsPurchaseRegisterRoute: typeof AppReportsPurchaseRegisterRoute
  AppReportsReceivablesRoute: typeof AppReportsReceivablesRoute
  AppReportsSalesRegisterRoute: typeof AppReportsSalesRegisterRoute
  AppReportsStockSummaryRoute: typeof AppReportsStockSummaryRoute
  AppReportsTradingRoute: typeof AppReportsTradingRoute
  AppReportsTrialBalanceRoute: typeof AppReportsTrialBalanceRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsAgeingRoute: AppReportsAgeingRoute,
  AppReportsBalanceSheetRoute: AppReportsBalanceSheetRoute,
  AppReportsBrsRoute: AppReportsBrsRoute,
  AppReportsCashBankRoute: AppReportsCashBankRoute,
  AppReportsDayBookRoute: AppReportsDayBookRoute,
  AppReportsGroupLedgerRoute: AppReportsGroupLedgerRoute,
  AppReportsGstPurchaseBookRoute: AppReportsGstPurchaseBookRoute,
  AppReportsGstSalesBookRoute: AppReportsGstSalesBookRoute,
  AppReportsGstr1Route: AppReportsGstr1Route,
  AppReportsGstr2bRoute: AppReportsGstr2bRoute,
  AppReportsGstr3bRoute: AppReportsGstr3bRoute,
  AppReportsLedgerRoute: AppReportsLedgerRoute,
  AppReportsOutstandingRoute: AppReportsOutstandingRoute,
  AppReportsPayablesRoute: AppReportsPayablesRoute,
  AppReportsProfitLossRoute: AppReportsProfitLossRoute,
  AppReportsPurchaseRegisterRoute: AppReportsPurchaseRegisterRoute,
  AppReportsReceivablesRoute: AppReportsReceivablesRoute,
  AppReportsSalesRegisterRoute: AppReportsSalesRegisterRoute,
  AppReportsStockSummaryRoute: AppReportsStockSummaryRoute,
  AppReportsTradingRoute: AppReportsTradingRoute,
  AppReportsTrialBalanceRoute: AppReportsTrialBalanceRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppVouchersRouteChildren {
  AppVouchersVoucherIdRoute: typeof AppVouchersVoucherIdRoute
  AppVouchersNewCredit_noteRoute: typeof AppVouchersNewCredit_noteRoute
  AppVouchersNewDebit_noteRoute: typeof AppVouchersNewDebit_noteRoute
  AppVouchersNewDelivery_noteRoute: typeof AppVouchersNewDelivery_noteRoute
  AppVouchersNewJournalRoute: typeof AppVouchersNewJournalRoute
  AppVouchersNewManufacturingRoute: typeof AppVouchersNewManufacturingRoute
  AppVouchersNewPaymentRoute: typeof AppVouchersNewPaymentRoute
  AppVouchersNewPurchaseRoute: typeof AppVouchersNewPurchaseRoute
  AppVouchersNewQuotationRoute: typeof AppVouchersNewQuotationRoute
  AppVouchersNewReceiptRoute: typeof AppVouchersNewReceiptRoute
  AppVouchersNewSalesRoute: typeof AppVouchersNewSalesRoute
  AppVouchersNewSales_orderRoute: typeof AppVouchersNewSales_orderRoute
}

const AppVouchersRouteChildren: AppVouchersRouteChildren = {
  AppVouchersVoucherIdRoute: AppVouchersVoucherIdRoute,
  AppVouchersNewCredit_noteRoute: AppVouchersNewCredit_noteRoute,
  AppVouchersNewDebit_noteRoute: AppVouchersNewDebit_noteRoute,
  AppVouchersNewDelivery_noteRoute: AppVouchersNewDelivery_noteRoute,
  AppVouchersNewJournalRoute: AppVouchersNewJournalRoute,
  AppVouchersNewManufacturingRoute: AppVouchersNewManufacturingRoute,
  AppVouchersNewPaymentRoute: AppVouchersNewPaymentRoute,
  AppVouchersNewPurchaseRoute: AppVouchersNewPurchaseRoute,
  AppVouchersNewQuotationRoute: AppVouchersNewQuotationRoute,
  AppVouchersNewReceiptRoute: AppVouchersNewReceiptRoute,
  AppVouchersNewSalesRoute: AppVouchersNewSalesRoute,
  AppVouchersNewSales_orderRoute: AppVouchersNewSales_orderRoute,
}

const AppVouchersRouteWithChildren = AppVouchersRoute._addFileChildren(
  AppVouchersRouteChildren,
)

interface AppRouteChildren {
  AppAccountGroupsRoute: typeof AppAccountGroupsRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppBankRoute: typeof AppBankRoute
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppEinvoiceRoute: typeof AppEinvoiceRoute
  AppHousekeepingRoute: typeof AppHousekeepingRoute
  AppItemsRoute: typeof AppItemsRoute
  AppLedgersRoute: typeof AppLedgersRoute
  AppRecurringRoute: typeof AppRecurringRoute
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppVouchersRoute: typeof AppVouchersRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountGroupsRoute: AppAccountGroupsRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppBankRoute: AppBankRoute,
  AppCompaniesRoute: AppCompaniesRoute,
  AppEinvoiceRoute: AppEinvoiceRoute,
  AppHousekeepingRoute: AppHousekeepingRoute,
  AppItemsRoute: AppItemsRoute,
  AppLedgersRoute: AppLedgersRoute,
  AppRecurringRoute: AppRecurringRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppVouchersRoute: AppVouchersRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
