/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVouchersRouteImport } from './routes/app.vouchers'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppLedgersRouteImport } from './routes/app.ledgers'
import { Route as AppItemsRouteImport } from './routes/app.items'
import { Route as AppCompaniesRouteImport } from './routes/app.companies'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVouchersRoute = AppVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgersRoute = AppLedgersRouteImport.update({
  id: '/ledgers',
  path: '/ledgers',
  getParentRoute: () => AppRoute,
} as any)
const AppItemsRoute = AppItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/items': typeof AppItemsRoute
  '/app/ledgers': typeof AppLedgersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/vouchers': typeof AppVouchersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/items': typeof AppItemsRoute
  '/app/ledgers': typeof AppLedgersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/vouchers': typeof AppVouchersRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/items': typeof AppItemsRoute
  '/app/ledgers': typeof AppLedgersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/vouchers': typeof AppVouchersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/companies'
    | '/app/items'
    | '/app/ledgers'
    | '/app/reports'
    | '/app/settings'
    | '/app/vouchers'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/companies'
    | '/app/items'
    | '/app/ledgers'
    | '/app/reports'
    | '/app/settings'
    | '/app/vouchers'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/companies'
    | '/app/items'
    | '/app/ledgers'
    | '/app/reports'
    | '/app/settings'
    | '/app/vouchers'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vouchers': {
      id: '/app/vouchers'
      path: '/vouchers'
      fullPath: '/app/vouchers'
      preLoaderRoute: typeof AppVouchersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ledgers': {
      id: '/app/ledgers'
      path: '/ledgers'
      fullPath: '/app/ledgers'
      preLoaderRoute: typeof AppLedgersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/items': {
      id: '/app/items'
      path: '/items'
      fullPath: '/app/items'
      preLoaderRoute: typeof AppItemsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/companies': {
      id: '/app/companies'
      path: '/companies'
      fullPath: '/app/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppItemsRoute: typeof AppItemsRoute
  AppLedgersRoute: typeof AppLedgersRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVouchersRoute: typeof AppVouchersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompaniesRoute: AppCompaniesRoute,
  AppItemsRoute: AppItemsRoute,
  AppLedgersRoute: AppLedgersRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVouchersRoute: AppVouchersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
